/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    'fact-checks': FactCheck;
    videos: Video;
    authors: Author;
    categories: Category;
    tags: Tag;
    leaders: Leader;
    parties: Party;
    polls: Poll;
    comments: Comment;
    readers: Reader;
    bookmarks: Bookmark;
    'poll-votes': PollVote;
    waitlist: Waitlist;
    submissions: Submission;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'fact-checks': FactChecksSelect<false> | FactChecksSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    leaders: LeadersSelect<false> | LeadersSelect<true>;
    parties: PartiesSelect<false> | PartiesSelect<true>;
    polls: PollsSelect<false> | PollsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    readers: ReadersSelect<false> | ReadersSelect<true>;
    bookmarks: BookmarksSelect<false> | BookmarksSelect<true>;
    'poll-votes': PollVotesSelect<false> | PollVotesSelect<true>;
    waitlist: WaitlistSelect<false> | WaitlistSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL path — leave empty to auto-generate
   */
  slug?: string | null;
  language: 'en' | 'hi';
  /**
   * Small label above the headline, e.g. "Parliament"
   */
  kicker?: string | null;
  /**
   * One-paragraph summary — shown on cards and in search results
   */
  excerpt: string;
  /**
   * Main image — alt text is set on the media itself
   */
  heroImage?: (number | null) | Media;
  imageCaption?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: number | Category;
  tags?: (number | Tag)[] | null;
  author: number | Author;
  verification?: ('verified' | 'sourced' | 'developing') | null;
  /**
   * How many independent sources back this story
   */
  sourceCount?: number | null;
  /**
   * Linked fact-check, if this story includes a verified claim
   */
  factCheck?: (number | null) | FactCheck;
  /**
   * Powers "In the news" on leader profiles and related-content matching
   */
  mentionedLeaders?: (number | Leader)[] | null;
  mentionedParties?: (number | Party)[] | null;
  /**
   * Hand-picked related stories (overrides automatic matching)
   */
  related?: (number | Article)[] | null;
  /**
   * If this is a translation, link the original article
   */
  translationOf?: (number | null) | Article;
  isExclusive?: boolean | null;
  publishedAt?: string | null;
  views?: number | null;
  /**
   * Computed from body length
   */
  readMinutes?: number | null;
  wordCount?: number | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO — what does it show?
   */
  alt: string;
  /**
   * Photographer / agency credit (optional)
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  label: string;
  /**
   * Shown to Hindi readers — same category, bilingual label
   */
  labelHi?: string | null;
  /**
   * URL path — leave empty to auto-generate
   */
  slug?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  label: string;
  labelHi?: string | null;
  /**
   * URL path — leave empty to auto-generate
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * URL path — leave empty to auto-generate
   */
  slug?: string | null;
  /**
   * e.g. @ananya
   */
  handle?: string | null;
  /**
   * e.g. Political Editor
   */
  role?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fact-checks".
 */
export interface FactCheck {
  id: number;
  /**
   * The claim being checked, quoted as it circulated
   */
  claim: string;
  /**
   * URL path — leave empty to auto-generate
   */
  slug?: string | null;
  language: 'en' | 'hi';
  /**
   * Who made the claim
   */
  claimant: string;
  rating: 'true' | 'mostly-true' | 'misleading' | 'false' | 'satire';
  /**
   * Plain-language verdict paragraph
   */
  verdict: string;
  evidence?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The viral image/screenshot under review
   */
  image?: (number | null) | Media;
  author: number | Author;
  publishedAt?: string | null;
  views?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leaders".
 */
export interface Leader {
  id: number;
  name: string;
  /**
   * URL path — leave empty to auto-generate
   */
  slug?: string | null;
  party: number | Party;
  /**
   * e.g. Member of Parliament
   */
  position?: string | null;
  constituency?: string | null;
  state?:
    | (
        | 'Maharashtra'
        | 'Uttar Pradesh'
        | 'Tamil Nadu'
        | 'Karnataka'
        | 'West Bengal'
        | 'Gujarat'
        | 'Bihar'
        | 'Madhya Pradesh'
        | 'Rajasthan'
        | 'Telangana'
        | 'Delhi'
        | 'Kerala'
        | 'Punjab'
        | 'Haryana'
        | 'Odisha'
        | 'Andhra Pradesh'
        | 'Assam'
        | 'Jharkhand'
        | 'Chhattisgarh'
        | 'Uttarakhand'
      )
    | null;
  age?: number | null;
  photo?: (number | null) | Media;
  bio?: string | null;
  rating?: number | null;
  followers?: number | null;
  /**
   * % in house
   */
  attendance?: number | null;
  questionsAsked?: number | null;
  /**
   * e.g. ₹12.4 Cr (from affidavit)
   */
  netWorth?: string | null;
  criminalCases?: number | null;
  education?: string | null;
  socials?: {
    /**
     * handle only, no @
     */
    twitter?: string | null;
    instagram?: string | null;
    facebook?: string | null;
    web?: string | null;
  };
  promises?:
    | {
        text: string;
        status: 'kept' | 'in-progress' | 'broken' | 'unverifiable';
        madeOn?: string | null;
        context?: string | null;
        /**
         * Link to the record backing this status — accountability needs receipts
         */
        sourceUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  timeline?:
    | {
        date: string;
        kind: 'milestone' | 'election' | 'controversy' | 'statement';
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parties".
 */
export interface Party {
  id: number;
  name: string;
  /**
   * Abbreviation, e.g. BJVP
   */
  short: string;
  /**
   * URL path — leave empty to auto-generate
   */
  slug?: string | null;
  /**
   * Party brand color (hex). Used only for dots/bars, never as text color.
   */
  color: string;
  founded?: number | null;
  ideology?: string[] | null;
  leader?: string | null;
  /**
   * Current Lok Sabha seats
   */
  seats?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'author';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  /**
   * URL path — leave empty to auto-generate
   */
  slug?: string | null;
  /**
   * The 11-character YouTube video ID (from the URL)
   */
  youtubeId: string;
  description?: string | null;
  /**
   * Auto-filled from YouTube; override if needed
   */
  thumbnailUrl?: string | null;
  /**
   * e.g. 12:45
   */
  duration?: string | null;
  series?: string | null;
  host?: string | null;
  /**
   * "Watch the video report" cross-link
   */
  relatedArticle?: (number | null) | Article;
  source?: ('manual' | 'youtube') | null;
  featured?: boolean | null;
  publishedAt?: string | null;
  views?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "polls".
 */
export interface Poll {
  id: number;
  question: string;
  /**
   * URL path — leave empty to auto-generate
   */
  slug?: string | null;
  description?: string | null;
  category: 'politics' | 'elections' | 'opinion' | 'trending';
  /**
   * Optional — for state-specific polls
   */
  state?:
    | (
        | 'Maharashtra'
        | 'Uttar Pradesh'
        | 'Tamil Nadu'
        | 'Karnataka'
        | 'West Bengal'
        | 'Gujarat'
        | 'Bihar'
        | 'Madhya Pradesh'
        | 'Rajasthan'
        | 'Telangana'
        | 'Delhi'
        | 'Kerala'
        | 'Punjab'
        | 'Haryana'
        | 'Odisha'
        | 'Andhra Pradesh'
        | 'Assam'
        | 'Jharkhand'
        | 'Chhattisgarh'
        | 'Uttarakhand'
      )
    | null;
  options: {
    label: string;
    votes?: number | null;
    /**
     * Optional hex; defaults to brand color
     */
    color?: string | null;
    id?: string | null;
  }[];
  totalVotes?: number | null;
  endsAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Moderation queue — approve or reject pending comments.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  body: string;
  article: number | Article;
  reader: number | Reader;
  status: 'pending' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * Created automatically when someone signs in with Google.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "readers".
 */
export interface Reader {
  id: number;
  email: string;
  name?: string | null;
  avatarUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks".
 */
export interface Bookmark {
  id: number;
  reader: number | Reader;
  article: number | Article;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poll-votes".
 */
export interface PollVote {
  id: number;
  poll: number | Poll;
  reader: number | Reader;
  optionId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter interest list. Nothing is sent to these addresses yet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist".
 */
export interface Waitlist {
  id: number;
  email: string;
  /**
   * Which form captured it (footer, cta, newsletter page)
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reader messages: contact, claims to fact-check, ad enquiries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  kind: 'contact' | 'claim' | 'advertising';
  status: 'new' | 'in-progress' | 'closed';
  /**
   * Auto-generated preview for the list view
   */
  summary?: string | null;
  name?: string | null;
  email?: string | null;
  subject?: string | null;
  message: string;
  /**
   * Where the reader saw the claim (fact-check submissions)
   */
  sourceUrl?: string | null;
  /**
   * Internal notes — never shown to the reader
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'fact-checks';
        value: number | FactCheck;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'leaders';
        value: number | Leader;
      } | null)
    | ({
        relationTo: 'parties';
        value: number | Party;
      } | null)
    | ({
        relationTo: 'polls';
        value: number | Poll;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'readers';
        value: number | Reader;
      } | null)
    | ({
        relationTo: 'bookmarks';
        value: number | Bookmark;
      } | null)
    | ({
        relationTo: 'poll-votes';
        value: number | PollVote;
      } | null)
    | ({
        relationTo: 'waitlist';
        value: number | Waitlist;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  language?: T;
  kicker?: T;
  excerpt?: T;
  heroImage?: T;
  imageCaption?: T;
  body?: T;
  category?: T;
  tags?: T;
  author?: T;
  verification?: T;
  sourceCount?: T;
  factCheck?: T;
  mentionedLeaders?: T;
  mentionedParties?: T;
  related?: T;
  translationOf?: T;
  isExclusive?: T;
  publishedAt?: T;
  views?: T;
  readMinutes?: T;
  wordCount?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fact-checks_select".
 */
export interface FactChecksSelect<T extends boolean = true> {
  claim?: T;
  slug?: T;
  language?: T;
  claimant?: T;
  rating?: T;
  verdict?: T;
  evidence?:
    | T
    | {
        point?: T;
        id?: T;
      };
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  image?: T;
  author?: T;
  publishedAt?: T;
  views?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  youtubeId?: T;
  description?: T;
  thumbnailUrl?: T;
  duration?: T;
  series?: T;
  host?: T;
  relatedArticle?: T;
  source?: T;
  featured?: T;
  publishedAt?: T;
  views?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  handle?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  label?: T;
  labelHi?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  label?: T;
  labelHi?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leaders_select".
 */
export interface LeadersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  party?: T;
  position?: T;
  constituency?: T;
  state?: T;
  age?: T;
  photo?: T;
  bio?: T;
  rating?: T;
  followers?: T;
  attendance?: T;
  questionsAsked?: T;
  netWorth?: T;
  criminalCases?: T;
  education?: T;
  socials?:
    | T
    | {
        twitter?: T;
        instagram?: T;
        facebook?: T;
        web?: T;
      };
  promises?:
    | T
    | {
        text?: T;
        status?: T;
        madeOn?: T;
        context?: T;
        sourceUrl?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        date?: T;
        kind?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parties_select".
 */
export interface PartiesSelect<T extends boolean = true> {
  name?: T;
  short?: T;
  slug?: T;
  color?: T;
  founded?: T;
  ideology?: T;
  leader?: T;
  seats?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "polls_select".
 */
export interface PollsSelect<T extends boolean = true> {
  question?: T;
  slug?: T;
  description?: T;
  category?: T;
  state?: T;
  options?:
    | T
    | {
        label?: T;
        votes?: T;
        color?: T;
        id?: T;
      };
  totalVotes?: T;
  endsAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  body?: T;
  article?: T;
  reader?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "readers_select".
 */
export interface ReadersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  avatarUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks_select".
 */
export interface BookmarksSelect<T extends boolean = true> {
  reader?: T;
  article?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poll-votes_select".
 */
export interface PollVotesSelect<T extends boolean = true> {
  poll?: T;
  reader?: T;
  optionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist_select".
 */
export interface WaitlistSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  kind?: T;
  status?: T;
  summary?: T;
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  sourceUrl?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  /**
   * Real handles — these feed the footer and share links
   */
  socials?: {
    /**
     * handle only, no @
     */
    instagram?: string | null;
    /**
     * channel handle, e.g. @thequiverindia
     */
    youtube?: string | null;
    /**
     * UC… id — needed for the video auto-sync feed
     */
    youtubeChannelId?: string | null;
    x?: string | null;
    facebook?: string | null;
    linkedin?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  socials?:
    | T
    | {
        instagram?: T;
        youtube?: T;
        youtubeChannelId?: T;
        x?: T;
        facebook?: T;
        linkedin?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}